### PR TITLE
Add more test cases for abstract methods of traits

### PR DESCRIPTION
**Pull request by herndlm**
this looks as expected though, doesn't it? nothing is removed..

### CODE REVIEW

**Comment by szepeviktor** [comment]
Could you add one of the methods from a trait?

**Comment by szepeviktor** [comment]
Could you actually use the trait in one of the classes?

**Comment by herndlm** [comment]
sorry Viktor, this does not fix anything whatsoever. the trait is fine IMO, the reason is that protected methods are removed from final classes IMO, because I did not think that those files are going to be executed. see https://github.com/php-stubs/woocommerce-stubs/issues/20#issuecomment-1436038690
when we execute them we shouldn't remove anything I guess

**Comment by herndlm** [comment]
but I'll add a trait usage, at least the tests got better then

**Comment by szepeviktor** [comment]
Thank you @herndlm!

**Pull request merged**
